ALTER SYSTEM SET AUDIT_TRAIL=DB SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP;

show parameter audit;

CREATE PLUGGABLE DATABASE banking
ADMIN USER admin IDENTIFIED BY 123456
ROLES = (DBA)
FILE_NAME_CONVERT = ('pdbseed', 'banking');


ALTER PLUGGABLE DATABASE banking OPEN;
ALTER PLUGGABLE DATABASE banking SAVE STATE;


ALTER SESSION SET CONTAINER = banking;
ALTER USER admin QUOTA UNLIMITED ON SYSTEM;

GRANT EXECUTE ON DBMS_RLS TO admin;

CREATE USER kh1 IDENTIFIED BY 123456;
CREATE USER kh2 IDENTIFIED BY 123456;
CREATE USER nv1 IDENTIFIED BY 123456;
CREATE USER gd1 IDENTIFIED BY 123456;


GRANT CREATE SESSION TO kh1, kh2, nv1, nv2,gd1;


CONN admin/123456@localhost:1521/banking;

-- 1. Bảng Khách Hàng
CREATE TABLE customer_info (
    username VARCHAR2(30) PRIMARY KEY,
    fullname VARCHAR2(50),
    cccd VARCHAR2(12),
    phone VARCHAR2(10),
    CONSTRAINT chk_cccd CHECK (REGEXP_LIKE(cccd, '^[0-9]{12}$')),
    CONSTRAINT chk_phone CHECK (REGEXP_LIKE(phone, '^[0-9]{10}$'))
);

-- 2. Bảng Tài Khoản (1 Khách hàng có thể có nhiều dòng ở đây)
CREATE TABLE account_balance (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID tài khoản (số tài khoản)
    username VARCHAR2(30) REFERENCES customer_info(username),
    balance NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT chk_acc_status CHECK (status IN ('active', 'locked'))
);

-- 3. Bảng Phiếu Giao Dịch (Gắn với Account ID cụ thể)
CREATE TABLE transaction_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES account_balance(id), -- Giao dịch của tài khoản nào
    username VARCHAR2(30) REFERENCES customer_info(username), -- Để dễ phân quyền VPD
    amount NUMBER,
    type VARCHAR2(10), -- DEPOSIT/WITHDRAW
    req_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'pending',
    CONSTRAINT chk_trans_status CHECK (status IN ('pending', 'accepted', 'cancel')),
    CONSTRAINT chk_trans_type CHECK (type IN ('DEPOSIT', 'WITHDRAW'))
);

-- 4. Bảng Nhân Viên
CREATE TABLE employee_info (
    emp_username VARCHAR2(30) PRIMARY KEY,
    salary NUMBER,
    position VARCHAR2(20)
);



-- Trigger 1: Chặn rút tiền nếu số dư của TÀI KHOẢN ĐÓ không đủ
CREATE OR REPLACE TRIGGER trg_check_withdraw
BEFORE INSERT ON transaction_log
FOR EACH ROW
DECLARE
    v_bal NUMBER;
BEGIN
    IF :NEW.type = 'WITHDRAW' THEN
        -- Lấy số dư của đúng account_id đang giao dịch
        SELECT balance INTO v_bal FROM account_balance WHERE id = :NEW.account_id;
        
        IF :NEW.amount > v_bal THEN
            RAISE_APPLICATION_ERROR(-20001, 'Số dư tài khoản này không đủ!');
        END IF;
    END IF;
END;
/

-- Trigger 2: Cập nhật tiền vào đúng Account ID khi duyệt
CREATE OR REPLACE TRIGGER trg_update_balance
AFTER UPDATE OF status ON transaction_log
FOR EACH ROW
WHEN (NEW.status = 'accepted' AND OLD.status != 'accepted')
BEGIN
    IF :NEW.type = 'DEPOSIT' THEN
        UPDATE account_balance SET balance = balance + :NEW.amount WHERE id = :NEW.account_id;
    ELSIF :NEW.type = 'WITHDRAW' THEN
        UPDATE account_balance SET balance = balance - :NEW.amount WHERE id = :NEW.account_id;
    END IF;
END;
/


-- 1. Bảng CUSTOMER_INFO
GRANT SELECT, UPDATE ON customer_info TO kh1, kh2;
GRANT SELECT, INSERT ON customer_info TO nv1, gd1;


-- 1. Bảng CUSTOMER_INFO
GRANT SELECT, UPDATE ON customer_info TO kh1, kh2;
GRANT SELECT, INSERT ON customer_info TO nv1, gd1;

-- 2. Bảng ACCOUNT_BALANCE
GRANT SELECT ON account_balance TO kh1, kh2;
GRANT SELECT, INSERT ON account_balance TO nv1;
GRANT SELECT ON account_balance TO gd1;
GRANT UPDATE (status) ON account_balance TO gd1;

-- 3. Bảng TRANSACTION_LOG
GRANT SELECT ON transaction_log TO kh1, kh2;
GRANT SELECT, INSERT ON transaction_log TO nv1;
GRANT SELECT, INSERT ON transaction_log TO gd1;
GRANT UPDATE (status) ON transaction_log TO gd1;

-- 4. Bảng EMPLOYEE_INFO
GRANT SELECT ON employee_info TO nv1;
GRANT SELECT, INSERT, UPDATE ON employee_info TO gd1;




-- Seed data more
INSERT INTO customer_info VALUES ('kh2', 'Tran Van B', '098765432109', '0912345678');
INSERT INTO customer_info VALUES ('kh1', 'Nguyen Van A', '012345678901', '0901234567');


INSERT INTO account_balance (username, balance) VALUES ('kh1', 0);       -- Tài khoản 1 (ID tự sinh: 1)
INSERT INTO account_balance (username, balance) VALUES ('kh1', 500000);  -- Tài khoản 2 (ID tự sinh: 2)
INSERT INTO account_balance (username, balance) VALUES ('kh2', 200000); -- Acc ID 3


INSERT INTO employee_info VALUES ('nv1', 1000, 'STAFF');
INSERT INTO employee_info VALUES ('gd1', 5000, 'DIRECTOR');








-- VPD1: KH
CREATE OR REPLACE FUNCTION fn_auth_customer (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 AS
    v_user VARCHAR2(30);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    -- NV, GD, Admin thấy hết
    IF v_user IN ('NV1', 'GD1', 'ADMIN') THEN
        RETURN NULL; 
    -- Khách hàng chỉ thấy dòng có username của mình
    ELSE 
        RETURN 'UPPER(username) = ''' || v_user || ''''; 
    END IF;
END;
/

-- Áp dụng Policy
BEGIN
    DBMS_RLS.ADD_POLICY('ADMIN', 'CUSTOMER_INFO', 'pol_cust_info', 'ADMIN', 'fn_auth_customer', 'SELECT, UPDATE');
    DBMS_RLS.ADD_POLICY('ADMIN', 'ACCOUNT_BALANCE', 'pol_cust_acc', 'ADMIN', 'fn_auth_customer', 'SELECT');
    DBMS_RLS.ADD_POLICY('ADMIN', 'TRANSACTION_LOG', 'pol_cust_trans', 'ADMIN', 'fn_auth_customer', 'SELECT');
END;
/




--VPD2: NV
CREATE OR REPLACE FUNCTION fn_auth_salary (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 AS
    v_user VARCHAR2(30);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF v_user IN ('GD1', 'ADMIN') THEN
        RETURN NULL;
    ELSE
        RETURN 'UPPER(emp_username) = ''' || v_user || '''';
    END IF;
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
        object_schema => 'ADMIN',
        object_name => 'EMPLOYEE_INFO',
        policy_name => 'pol_emp_salary',
        function_schema => 'ADMIN',
        policy_function => 'fn_auth_salary',
        statement_types => 'SELECT',
        sec_relevant_cols => 'SALARY',
        sec_relevant_cols_opt => DBMS_RLS.ALL_ROWS
    );
END;
/


----- Audit -----

CONN admin/123456@localhost:1521/banking;
SHOW PARAMETER AUDIT_TRAIL; -- Neu hien value: DB thi thanh cong --


-- Tạo Policy giám sát hành động trên 4 bảng--
CREATE AUDIT POLICY giam_sat_banking
    ACTIONS ALL ON admin.customer_info,
            ALL ON admin.account_balance,
            ALL ON admin.transaction_log,
            ALL ON admin.employee_info;
            
-- Bật Policy cho tất cả user
AUDIT POLICY giam_sat_banking;



---Password--

---- Profie pass word -------

CONN admin/123456@localhost:1521/banking;

CREATE PROFILE banking_security LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1/24
    PASSWORD_LIFE_TIME 90
    PASSWORD_GRACE_TIME 7
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 5;
    
--------- Tạo Profile---------
-- 1. Chống dò mật khẩu (Brute-force)
-- Nhập sai 3 lần là khóa
-- Khóa trong 1 giờ (1 ngày / 24)
-- 2. Ép buộc thay đổi định kỳ (Password Expiration)
-- Mật khẩu sống 90 ngày
-- Cảnh báo đổi pass trước 7 ngày khi hết hạn
-- 3. Chống dùng lại mật khẩu cũ (Password History)
-- Không được dùng lại pass đã dùng trong 1 năm qua
-- Hoặc không trùng với 5 pass gần nhất




ALTER USER kh1 PROFILE banking_security;
ALTER USER kh2 PROFILE banking_security;
ALTER USER nv1 PROFILE banking_security;
ALTER USER gd1 PROFILE banking_security;

- Mo khoa neu dang nhap qua 3 lan ko dc ---
CONN admin/123456@localhost:1521/banking;
ALTER USER kh1 ACCOUNT UNLOCK;

-------
IV. Tổng kết
Với thiết kế này, hệ thống của bạn đã đạt được các tiêu chuẩn an toàn cơ bản:

Chặn đứng dò pass: Hacker chỉ thử được 3 lần là bị khóa 1 tiếng.

Loại bỏ mật khẩu vĩnh viễn: Sau 3 tháng buộc phải đổi mới.

Quy trình cấp phát an toàn: User mới phải tự đặt lại mật khẩu của riêng họ.







----------------------------------------- Test ---------------------------------------------------------
--------------------------------------------------------------------------------------------------------


-- Test contrainst:
-- Test 1: Insert sai SĐT (chữ cái hoặc thiếu số) -> Kỳ vọng LỖI
INSERT INTO customer_info VALUES ('test_user', 'Test Name', '000000000001', 'abc');


-- Test trigger
-- KH1 có: Acc 1 (0đ), Acc 2 (500k)
INSERT INTO transaction_log (account_id, username, amount, type) VALUES (1, 'kh1', 100000, 'WITHDRAW');
-- ORA-20001: Số dư tài khoản này không đủ!
-- Test 2: Rút 100k từ Acc 2 -> Kỳ vọng THÀNH CÔNG (Pending)
INSERT INTO transaction_log (account_id, username, amount, type) VALUES (2, 'kh1', 100000, 'WITHDRAW');
-- Test 3: Duyệt phiếu Acc 2 -> Tiền Acc 2 giảm còn 400k
UPDATE transaction_log SET status = 'accepted' WHERE account_id = 2;
SELECT * FROM account_balance WHERE username = 'kh1';
-- Kết quả: Acc 1 (0), Acc 2 (400000)



-- Test vpd
-- Test 1: KH1 xem danh sách tài khoản
CONN kh1/123456@//localhost:1521/banking;
SELECT * FROM admin.account_balance;
-- Kỳ vọng: Thấy 2 dòng (Acc 1 và Acc 2). Không thấy Acc 3 của KH2.

-- Test 2: KH2 xem danh sách tài khoản
CONN kh2/123456@//localhost:1521/banking;
SELECT * FROM admin.account_balance;
-- Kỳ vọng: Chỉ thấy 1 dòng (Acc 3).

-- Test 3: NV1 xem danh sach employee:
CONN nv1/123456@//localhost:1521/banking;
SELECT * FROM admin.employee_info;





---Test Audit----
-- Test Audit o user admin ---

CONN kh1/123456@//localhost:1521/banking;
SELECT * FROM admin.account_balance;

CONN nv1/123456@//localhost:1521/banking;
INSERT INTO admin.transaction_log (account_id, username, amount, type) 
VALUES (1, 'kh1', 50000, 'DEPOSIT'); 

CONN gd1/123456@//localhost:1521/banking;
UPDATE admin.transaction_log SET status = 'accepted' WHERE account_id = 1; 


CONN admin/123456@localhost:1521/banking;

SELECT 
    event_timestamp, 
    dbusername, 
    action_name, 
    object_name, 
    sql_text 
FROM unified_audit_trail 
WHERE object_name IN ('CUSTOMER_INFO', 'TRANSACTION_LOG', 'ACCOUNT_BALANCE', 'EMPLOYEE_INFO') -- Lưu ý: CHỮ IN HOA
ORDER BY event_timestamp DESC;



----Cach Tat Audit -----------

SELECT policy_name, enabled_option, entity_name 
FROM audit_unified_enabled_policies;
-- Kết quả sẽ hiện ra tên policy, ví dụ: GIAM_SAT_BANKING

-- Tắt policy giám sát (thay tên policy của bạn vào)
NOAUDIT POLICY giam_sat_banking;

--- Xóa hẳn Policy
DROP AUDIT POLICY giam_sat_banking;


--- Clean data trong bang unified audit trail
BEGIN
    DBMS_AUDIT_MGMT.CLEAN_AUDIT_TRAIL(
        audit_trail_type        => DBMS_AUDIT_MGMT.AUDIT_TRAIL_UNIFIED, -- Chỉ định loại Unified
        use_last_arch_timestamp => FALSE                                -- FALSE nghĩa là xóa hết, không cần quan tâm mốc thời gian lưu trữ
    );
END;
/















