-- Banking Database Schema Setup
-- Chạy với user admin trong PDB FREEPDB1

-- Set session (no need to alter session, already connected to FREEPDB1)
ALTER USER admin QUOTA UNLIMITED ON SYSTEM;
GRANT EXECUTE ON DBMS_RLS TO admin;

-- Create users
CREATE USER kh1 IDENTIFIED BY 123456;
CREATE USER kh2 IDENTIFIED BY 123456;
CREATE USER nv1 IDENTIFIED BY 123456;
CREATE USER gd1 IDENTIFIED BY 123456;

GRANT CREATE SESSION TO kh1, kh2, nv1, gd1;

-- 1. Bảng Khách Hàng
CREATE TABLE customer_info (
    username VARCHAR2(30) PRIMARY KEY,
    fullname VARCHAR2(50),
    cccd VARCHAR2(12),
    phone VARCHAR2(10),
    CONSTRAINT chk_cccd CHECK (REGEXP_LIKE(cccd, '^[0-9]{12}$')),
    CONSTRAINT chk_phone CHECK (REGEXP_LIKE(phone, '^[0-9]{10}$'))
);

-- 2. Bảng Tài Khoản
CREATE TABLE account_balance (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(30) REFERENCES customer_info(username),
    balance NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'active',
    CONSTRAINT chk_acc_status CHECK (status IN ('active', 'locked'))
);

-- 3. Bảng Phiếu Giao Dịch
CREATE TABLE transaction_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER REFERENCES account_balance(id),
    username VARCHAR2(30) REFERENCES customer_info(username),
    amount NUMBER,
    type VARCHAR2(10),
    req_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'pending',
    CONSTRAINT chk_trans_status CHECK (status IN ('pending', 'accepted', 'cancel')),
    CONSTRAINT chk_trans_type CHECK (type IN ('DEPOSIT', 'WITHDRAW'))
);

-- 4. Bảng Nhân Viên
CREATE TABLE employee_info (
    emp_username VARCHAR2(30) PRIMARY KEY,
    salary NUMBER,
    position VARCHAR2(20)
);

-- Trigger 1: Chặn rút tiền nếu số dư không đủ
CREATE OR REPLACE TRIGGER trg_check_withdraw
BEFORE INSERT ON transaction_log
FOR EACH ROW
DECLARE
    v_bal NUMBER;
BEGIN
    IF :NEW.type = 'WITHDRAW' THEN
        SELECT balance INTO v_bal FROM account_balance WHERE id = :NEW.account_id;

        IF :NEW.amount > v_bal THEN
            RAISE_APPLICATION_ERROR(-20001, 'Số dư tài khoản này không đủ!');
        END IF;
    END IF;
END;
/

-- Trigger 2: Cập nhật tiền vào đúng Account ID khi duyệt
CREATE OR REPLACE TRIGGER trg_update_balance
AFTER UPDATE OF status ON transaction_log
FOR EACH ROW
WHEN (NEW.status = 'accepted' AND OLD.status != 'accepted')
BEGIN
    IF :NEW.type = 'DEPOSIT' THEN
        UPDATE account_balance SET balance = balance + :NEW.amount WHERE id = :NEW.account_id;
    ELSIF :NEW.type = 'WITHDRAW' THEN
        UPDATE account_balance SET balance = balance - :NEW.amount WHERE id = :NEW.account_id;
    END IF;
END;
/

-- Grant permissions
-- CUSTOMER_INFO
GRANT SELECT, UPDATE ON customer_info TO kh1, kh2;
GRANT SELECT, INSERT ON customer_info TO nv1, gd1;

-- ACCOUNT_BALANCE
GRANT SELECT ON account_balance TO kh1, kh2;
GRANT SELECT, INSERT ON account_balance TO nv1;
GRANT SELECT ON account_balance TO gd1;
GRANT UPDATE (status) ON account_balance TO gd1;

-- TRANSACTION_LOG
GRANT SELECT ON transaction_log TO kh1, kh2;
GRANT SELECT, INSERT ON transaction_log TO nv1;
GRANT SELECT, INSERT ON transaction_log TO gd1;
GRANT UPDATE (status) ON transaction_log TO gd1;

-- EMPLOYEE_INFO
GRANT SELECT ON employee_info TO nv1;
GRANT SELECT, INSERT, UPDATE ON employee_info TO gd1;

-- Password Profile
CREATE PROFILE banking_security LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1/24
    PASSWORD_LIFE_TIME 90
    PASSWORD_GRACE_TIME 7
    PASSWORD_REUSE_TIME 365
    PASSWORD_REUSE_MAX 5;

ALTER USER kh1 PROFILE banking_security;
ALTER USER kh2 PROFILE banking_security;
ALTER USER nv1 PROFILE banking_security;
ALTER USER gd1 PROFILE banking_security;

COMMIT;
